### ISSUE TITLE
animated-navigation にアレンジを追加しよう

### ISSUE THREAD

**Issue by jp-knj** [monosus-bhsstt/learning-web-development#20]
# 課題

CSSのカスタムプロパティを活用しよう！

- [x] `:root 擬似クラス`にカスタムプロパティを定義して、色を管理してみてください！

以下のようにコーディングしてみてください！
```css
:root {
  --main-bg-color: brown;
}
```

```css
element {
  background-color: var(--main-bg-color);
}
```

[参考記事](https://developer.mozilla.org/ja/docs/Web/CSS/Using_CSS_custom_properties)
